version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:latest
    container_name: mongo_leadsmax
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: leadsmax_user
      MONGO_INITDB_ROOT_PASSWORD: leadsmax_pass
      MONGO_INITDB_DATABASE: leadsmax_db
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - leadsmax-network

  # MongoDB Express (Admin UI)
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_leadsmax
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: leadsmax_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: leadsmax_pass
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 12345678a
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    networks:
      - leadsmax-network

  # Backend API (NestJS)
  backend:
    build: 
      context: ./blog-data-BE
      dockerfile: Dockerfile
    container_name: leadsmax_backend
    restart: unless-stopped
    environment:
      MONGO_URI: mongodb://leadsmax_user:leadsmax_pass@mongo:27017/leadsmax_db?authSource=admin
      NODE_ENV: production
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - leadsmax-network
    volumes:
      - ./blog-data-BE:/app
      - /app/node_modules

  # Admin Frontend (Next.js)
  admin-frontend:
    build:
      context: ./blog-admin-FE
      dockerfile: Dockerfile
    container_name: leadsmax_admin_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000
      NODE_ENV: production
    ports:
      - '3001:3000'
    depends_on:
      - backend
    networks:
      - leadsmax-network
    volumes:
      - ./blog-admin-FE:/app
      - /app/node_modules
      - /app/.next

  # Landing Page Frontend (Nuxt.js)
  landing-frontend:
    build:
      context: ./lading-page-FE
      dockerfile: Dockerfile
    container_name: leadsmax_landing_frontend
    restart: unless-stopped
    environment:
      NUXT_PUBLIC_API_URL: http://backend:3000
      NODE_ENV: production
    ports:
      - '3002:3000'
    depends_on:
      - backend
    networks:
      - leadsmax-network
    volumes:
      - ./lading-page-FE:/app
      - /app/node_modules
      - /app/.nuxt

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: leadsmax_nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - admin-frontend
      - landing-frontend
    networks:
      - leadsmax-network

volumes:
  mongo_data:

networks:
  leadsmax-network:
    driver: bridge 